const base = [
  /// A
  { address: "Ada", location: "BORIK" },
  { address: "Adelin Irbi (vrbanja)", location: "MEJDAN" },
  { address: "Aleja sv. Save", location: "BORIK" },
  { address: "Aleja sv. Save 2 - 26", location: "TROPIK" },
  { address: "Alekse Šantića", location: "LAUŠ" },
  { address: "Alekse Dundića", location: "BUDŽAK" },
  { address: "Anđe Knežević", location: "TROPIK" },
  { address: "Anke Drakulić", location: "LAUŠ" },
  { address: "Arčibalda Rajsa", location: "MEJDAN" },
  { address: "Arsenija Čarnojevića", location: "MEJDAN" },
  { address: "Avalska (vrbanja)", location: "MEJDAN" },

  /// B
  { address: "Baje Pivljanina", location: "LAUŠ" },
  { address: "Bana Lazarevića", location: "BORIK" },
  { address: "Bana Milosavljevića", location: "BORIK" },
  { address: "Banijska", location: "TRANZIT" },
  { address: "Banović Strahinje", location: "MEJDAN" },
  { address: "Beogradska", location: "BORIK" },
  { address: "Bilećka", location: "BUDŽAK" },
  { address: "Bitoljska", location: "BUDŽAK" },
  { address: "Blagoja Parovića", location: "BUDŽAK" },
  { address: "Bogdana Marića", location: "TROPIK" },
  { address: "Bogdana Žerajića", location: "LAUŠ" },
  { address: "Bolanog Dojčina", location: "LAUŠ" },
  { address: "Bore Stankovića", location: "BORIK" },
  { address: "Bose Živković", location: "LAUŠ" },
  { address: "Boška Tošića", location: "MEJDAN" },
  { address: "Bože Nikolića", location: "TRANZIT" },
  { address: "Bože Varićaka", location: "TRANZIT" },
  { address: "Božidara Adžije", location: "LAUŠ" },
  { address: "Božidara Miće Babića", location: "LAUŠ" },
  { address: "Braće Čubrilović", location: "MEJDAN" },
  { address: "Braće i sestara Glumac", location: "BORIK" },
  { address: "Braće i sestara Oljača", location: "ČESMA" },
  { address: "Braće i sestra Kapor", location: "TROPIK" },
  { address: "Braće Jugovića", location: "MEJDAN" },
  { address: "Braće Kavića", location: "MEJDAN" },
  { address: "Braće Kukrika", location: "MEJDAN" },
  { address: "Braće Mažar i majke Marije", location: "TROPIK" },
  { address: "Braće Miletića", location: "MEJDAN" },
  { address: "Braće Pantića", location: "TROPIK" },
  { address: "Braće Pišteljića", location: "BUDŽAK" },
  { address: "Braće Podgornika", location: "BUDŽAK" },
  { address: "Brace Potkonjaka", location: "MEJDAN" },
  { address: "Branislava Nušića", location: "TRANZIT" },
  { address: "Branka Ćopića", location: "BORIK" },
  { address: "Branka Grbčića", location: "BUDŽAK" },
  { address: "Branka Koščice", location: "LAUŠ" },
  { address: "Branka Majstorovića", location: "TROPIK" },
  { address: "Branka Morače", location: "TROPIK" },
  { address: "Branka Perduva", location: "BUDŽAK" },
  { address: "Branka Popovića", location: "BUDŽAK" },
  { address: "Branka Radičevića", location: "TROPIK" },
  { address: "Branka Zagorca", location: "TROPIK" },
  { address: "Bulevar Cara Dušana", location: "TROPIK" },
  { address: "Bulevar Srpske Vojske", location: "BORIK" },
  /// C
  { address: "Cara Konstantina Velikog", location: "MEJDAN" },
  { address: "Cara Lazara", location: "MEJDAN" },
  { address: "Cara Lazara 2 - 18 (didaco)", location: "TROPIK" },
  { address: "Cara Nikolaja", location: "TROPIK" },
  { address: "Careva Romanovih", location: "TROPIK" },
  { address: "Carice Milice", location: "MEJDAN" },
  { address: "Cerska", location: "MEJDAN" },
  { address: "Cetinjska", location: "TROPIK" },
  /// D
  { address: "12 Beba", location: "LAUŠ" },
  { address: "Dalibora Dače Stojića ", location: "TRANZIT" },
  { address: "Darka Jakmirovića", location: "LAUŠ" },
  { address: "Davida Štrbca ", location: "TRANZIT" },
  { address: "Desanke Maksimović ", location: "MEJDAN" },
  { address: "Despota Konstantina Dragaša", location: "LAUŠ" },
  { address: "Despota Stefana Lazarevića ", location: "BUDŽAK" },
  { address: "Dobojska", location: "LAUŠ" },
  { address: "Đorđa Jovetića", location: "LAUŠ" },
  { address: "Dositeja Obradovića ", location: "BORIK" },
  { address: "Dragana Bubića ", location: "BUDŽAK" },
  { address: "Drage Malića ", location: "TROPIK" },
  { address: "Dragiše Vasića ", location: "TRANZIT" },
  { address: "Drvarska", location: "LAUŠ" },
  { address: "Dubička ", location: "BUDŽAK" },
  { address: "Dujke Komjenovića ", location: "MEJDAN" },
  { address: "Dunavska ", location: "BUDŽAK" },
  { address: "Đurđevića put (pavlovac)", location: "LAUŠ" },
  { address: "Đure Damjanovića (pavlovac)", location: "LAUŠ" },
  { address: "Đure Daničića ", location: "BORIK" },
  { address: "Đure Jakšića ", location: "TROPIK" },
  { address: "Dušana Diljevića", location: "LAUŠ" },
  { address: "Dušana I Vlade Kopanje", location: "LAUŠ" },
  { address: "Dušana Jokića", location: "LAUŠ" },
  { address: "Dušana Subotića", location: "LAUŠ" },
  { address: "Duška Koščice ", location: "TROPIK" },
  /// E
  { address: "Eugena Kumičića", location: "TRANZIT" },
  /// Č
  { address: "14 Srednjobosanske Brigade", location: "TRANZIT" },
  { address: "4 Krajiškog Partizanskog Odreda", location: "BUDŽAK" },
  { address: "Čaire", location: "TROPIK" },
  /// F
  { address: "Federika Garsije Lorke ", location: "TRANZIT" },
  { address: "Filipa Kljajića Fiće ", location: "LAUŠ" },
  { address: "Filipa Macure ", location: "TROPIK" },
  { address: "Frana Supila ", location: "BORIK" },
  { address: "Franca Šuberta ", location: "LAUŠ" },
  { address: "Fruškogorska ", location: "TRANZIT" },
  /// G
  { address: "Gajeva ", location: "BORIK" },
  { address: "Gavre Vučkovića ", location: "BORIK" },
  { address: "Gavrila Principa ", location: "MEJDAN" },
  { address: "Goluba Babića ", location: "BUDŽAK" },
  { address: "Gorana Radulovića Bimbe ", location: "BORIK" },
  { address: "Grčka ", location: "TROPIK" },
  { address: "Grmečka (derviši) ", location: "BUDŽAK" },
  { address: "Gundulićeva ", location: "BORIK" },
  /// H
  { address: "1300 Kaplara ", location: "LAUŠ" },
  { address: "Hajduk Veljka ", location: "BUDŽAK" },
  { address: "Hercegnovska ", location: "BUDŽAK" },
  { address: "Hvarska ", location: "TROPIK" },
  /// I
  { address: "Igmanska ", location: "TRANZIT" },
  { address: "Ilije Garašanina ", location: "BUDŽAK" },
  { address: "Ilije Grbića ", location: "LAUŠ" },
  { address: "Ilije Smiljanića ", location: "BUDŽAK" },
  { address: "Isaije Mitrovića ", location: "TROPIK" },
  { address: "Isidore Sekulić ", location: "TROPIK" },
  { address: "Ivana Franje Jukića ", location: "BORIK" },
  { address: "Ivana Kosančica ", location: "BUDŽAK" },
  { address: "Ivana Gorana Kovačića ", location: "BUDŽAK" },
  { address: "Ivana Kukuljevića ", location: "TRANZIT" },
  { address: "Ivana Milutinovića ", location: "ČESMA" },
  { address: "Ive Andrića ", location: "TROPIK" },
  { address: "Ive Lole Ribara ", location: "BORIK" },
  /// J
  { address: "Jadranska ", location: "BUDŽAK" },
  { address: "Jajačka/Velibora Janjetovića Janje ", location: "LAUŠ" },
  { address: "Janka Veselinovića ", location: "TRANZIT" },
  { address: "Jaroslava Hašeka ", location: "BUDŽAK" },
  { address: "Jaroslava Plecitija ", location: "TRANZIT" },
  { address: "Jaše Ignjatovića ", location: "TROPIK" },
  { address: "Jasenovačkih Logoraša ", location: "MEJDAN" },
  { address: "Jasimira Malčića ", location: "LAUŠ" },
  { address: "Jesenjinova ", location: "TROPIK" },
  { address: "Jevrejska ", location: "BORIK" },
  { address: "Josifa Pančića ", location: "MEJDAN" },
  { address: "Jovana Bijelića ", location: "BUDŽAK" },
  { address: "Jovana Cvijića ", location: "LAUŠ" },
  { address: "Jovana Dučića 25 - 44 ", location: "TROPIK" },
  { address: "Jovana Dučića ", location: "TRANZIT" },
  { address: "Jovana Jančića ", location: "MEJDAN" },
  { address: "Jovana Raškovića ", location: "LAUŠ" },
  { address: "Jovana Surutke ", location: "BORIK" },
  { address: "Jovane Milošević ", location: "TROPIK" },
  { address: "Jovanke Gajić Zmijanke ", location: "LAUŠ" },
  { address: "Jovice Savinovića ", location: "TRANZIT" },
  { address: "Jug Bogdana ", location: "MEJDAN" },
  /// K
  { address: "Kajmakčalanska ", location: "BUDŽAK" },
  { address: "Kalemegdanska ", location: "MEJDAN" },
  { address: "Karađorđeva ", location: "LAUŠ" },
  { address: "Ključka ", location: "LAUŠ" },
  { address: "Knežopoljska ", location: "BORIK" },
  { address: "Kninska ", location: "TROPIK" },
  { address: "Knjaza Miloša ", location: "BUDŽAK" },
  { address: "Kojića Put ", location: "BUDŽAK" },
  { address: "Kola Srpskih Sestara ", location: "LAUŠ" },
  { address: "Kolubarska ", location: "TROPIK" },
  { address: "Kordunaška ", location: "BORIK" },
  { address: "Kosovke Djevojke ", location: "MEJDAN" },
  { address: "Kosovska ", location: "LAUŠ" },
  { address: "Koste Abraševića ", location: "BUDŽAK" },
  { address: "Koste Jarića ", location: "MEJDAN" },
  { address: "Koste Krsmanovića ", location: "LAUŠ" },
  { address: "Koste Majkića ", location: "LAUŠ" },
  { address: "Koste Vojinovića ", location: "MEJDAN" },
  { address: "Kragujevačkih i Kraljevačkih žrtava ", location: "MEJDAN" },
  { address: "Krajiška ", location: "LAUŠ" },
  { address: "Krajiskih Brigada ", location: "TRANZIT" },
  { address: "Krajiskih Brigada do 113 N i 8 P ", location: "LAUŠ" },
  { address: "Kralja Aleksandra I ", location: "TRANZIT" },
  { address: "Kralja Alfonsa XIII ", location: "BORIK" },
  { address: "Kozarska ", location: "TROPIK" },
  { address: "Kutuzova ", location: "TROPIK" },
  { address: "Kralja Nikole ", location: "TROPIK" },
  {
    address: "Kralja Petra I Karadjordjevica do 119 N i 90 P ",
    location: "TROPIK",
  },
  { address: "Kralja Petra I Karadjordjevica ", location: "TRANZIT" },
  { address: "Kralja Petra II . ", location: "TRANZIT" },
  { address: "Kraljice Marije ", location: "BUDŽAK" },
  { address: "Krfska ", location: "MEJDAN" },
  { address: "Krušedolska (pavlovac) ", location: "LAUŠ" },
  { address: "Kupreška ", location: "TRANZIT" },
  /// L
  { address: "Lava Tolstoja ", location: "ČESMA" },
  { address: "Lazarička ", location: "TRANZIT" },
  { address: "Leskovačka ", location: "TRANZIT" },
  { address: "Lijevčanska ", location: "LAUŠ" },
  { address: "Lipovačka ", location: "BUDŽAK" },
  { address: "Ljubice Gerovac ", location: "LAUŠ" },
  { address: "Ljubice Mrkonjić ", location: "TRANZIT" },
  { address: "Ljubijskih Rudara ", location: "TRANZIT" },
  { address: "Lovćenska ", location: "BUDŽAK" },
  { address: "Ložionicka ", location: "BUDŽAK" },
  /// M
  { address: "Mačvanska ", location: "MEJDAN" },
  { address: "Majevička ", location: "TRANZIT" },
  { address: "Majke Jevrosime ", location: "LAUŠ" },
  { address: "Majke Jugovića ", location: "MEJDAN" },
  { address: "Majke Knežopoljke ", location: "BORIK" },
  { address: "Majke Kristine ", location: "TROPIK" },
  { address: "Majora Drage Bajalovića ", location: "BUDŽAK" },
  { address: "Maksima Gorkog ", location: "LAUŠ" },
  { address: "Manastira Gomionice ", location: "TROPIK" },
  { address: "Manastira Gračanice ", location: "MEJDAN" },
  { address: "Manastira Moštanice ", location: "TRANZIT" },
  { address: "Manjačkih Ustanika ", location: "TROPIK" },
  { address: "Marije Bursać ", location: "TROPIK" },
  { address: "Marije Dimić ", location: "TRANZIT" },
  { address: "Marka Cara ", location: "MEJDAN" },
  { address: "Marka Kraljevića ", location: "MEJDAN" },
  { address: "Marka Lipovca ", location: "BUDŽAK" },
  { address: "Marka Miljanova ", location: "BUDŽAK" },
  { address: "Masarikova ", location: "TRANZIT" },
  { address: "Meše Selimovića ", location: "TROPIK" },
  { address: "Miće Ljubibratića ", location: "BUDŽAK" },
  { address: "Miće Radakovića ", location: "TROPIK" },
  { address: "Mihajla Pupina ", location: "TROPIK" },
  { address: "Milana Brankovića ", location: "LAUŠ" },
  { address: "Milana Budimira ", location: "TROPIK" },
  { address: "Milana Cvjetića ", location: "BUDŽAK" },
  { address: "Monahinje Jefimije ", location: "BUDŽAK" },
  { address: "Milana Karanovića ", location: "BORIK" },
  { address: "Milana Knežine ", location: "TRANZIT" },
  { address: "Milana Mirica (kod kafea Biser) ", location: "BUDŽAK" },
  { address: "Milana Radmana ", location: "TRANZIT" },
  { address: "Milana Rakića ", location: "BORIK" },
  { address: "Milana Stevilovića ", location: "TRANZIT" },
  { address: "Milana Tepica ", location: "TROPIK" },
  { address: "Milana Toplice ", location: "BUDŽAK" },
  { address: "Milana Vasića ", location: "MEJDAN" },
  { address: "Mile Bekute ", location: "LAUŠ" },
  { address: "Mileševska ", location: "MEJDAN" },
  { address: "Milice Stojadinović Srpkinje ", location: "MEJDAN" },
  { address: "Milorada Umjenovića ", location: "LAUŠ" },
  { address: "Miloša Dujića ", location: "MEJDAN" },
  { address: "Miloša Matića ", location: "LAUŠ" },
  { address: "Miloša Obilića ", location: "MEJDAN" },
  { address: "Miloša Popovića Đurina ", location: "BUDŽAK" },
  { address: "Milovana Glišića ", location: "MEJDAN" },
  { address: "Mire Cikote ", location: "BUDŽAK" },
  { address: "Mirjane Jotanović ", location: "BUDŽAK" },
  { address: "Mirka Kovačevića ", location: "MEJDAN" },
  { address: "Miše Stupara ", location: "BORIK" },
  { address: "Mlađe Ćusića ", location: "BUDŽAK" },
  { address: "Mladena Oljače ", location: "TRANZIT" },
  { address: "Mladena Stojanovića ", location: "TRANZIT" },
  { address: "Modrička (šargovac) ", location: "BUDŽAK" },
  { address: "Mojkovačka ", location: "BUDŽAK" },
  { address: "Momčila Nastasijevića ", location: "TROPIK" },
  { address: "Momčila Popovića ", location: "LAUŠ" },
  { address: "Moravska ", location: "BUDŽAK" },
  { address: "Moslovačka ", location: "TRANZIT" },
  { address: "Muhameda Mehmedbašića ", location: "TROPIK" },
  /// N
  { address: "Nadežde Petrović ", location: "TROPIK" },
  { address: "Natalije Jović ", location: "TRANZIT" },
  { address: "Nedeljka Čabrinovića ", location: "TRANZIT" },
  { address: "Nikole Bokana ", location: "LAUŠ" },
  { address: "Nikole Pašića ", location: "BORIK" },
  { address: "Nikole Tesle ", location: "TROPIK" },
  { address: "Njegoševa ", location: "TRANZIT" },
  { address: "Novaka Pivaševića ", location: "MEJDAN" },
  { address: "Novice Cerovića ", location: "BORIK" },
  { address: "Novosadska ", location: "TRANZIT" },
  /// O
  { address: "Od Zmijanja Rajka ", location: "MEJDAN" },
  { address: "Omladinska ", location: "LAUŠ" },
  { address: "Ognjena Price ", location: "MEJDAN" },
  { address: "Olimpijskih pobjednika ", location: "TRANZIT" },
  { address: "Oplenačka ", location: "LAUŠ" },
  { address: "Orlovački put ", location: "MEJDAN" },
  /// P
  { address: "5. Prigradski Put ", location: "MEJDAN" },
  { address: "Palih Boraca ", location: "MEJDAN" },
  { address: "Patre ", location: "TROPIK" },
  { address: "Pave Radana ", location: "TRANZIT" },
  { address: "Pere Drljače ", location: "MEJDAN" },
  { address: "Pere Krece ", location: "MEJDAN" },
  { address: "Pere Sljepčevića ", location: "MEJDAN" },
  { address: "Pete Kozarske Brigade ", location: "TRANZIT" },
  { address: "Petra Bojovića ", location: "BORIK" },
  { address: "Petra Kočića ", location: "TRANZIT" },
  { address: "Petra Mećave ", location: "LAUŠ" },
  { address: "Petra Pecije ", location: "BUDŽAK" },
  { address: "Petra Preradovića ", location: "TRANZIT" },
  { address: "Petra Rađenovića ", location: "TRANZIT" },
  { address: "Petra Velikog ", location: "ČESMA" },
  { address: "Petrovačka ", location: "LAUŠ" },
  { address: "Pionirska ", location: "MEJDAN" },
  { address: "Podgorička (derviši) ", location: "BUDŽAK" },
  { address: "Podgrmečka ", location: "LAUŠ" },
  { address: "Ponirska ", location: "MEJDAN" },
  { address: "Popa Jovice ", location: "TROPIK" },
  { address: "Prote Nikole Kostića ", location: "BUDŽAK" },
  { address: "Prote Todora Srdića ", location: "MEJDAN" },
  { address: "Prote Vida Kovačevića ", location: "TROPIK" },
  { address: "Prve Krajiške Brigade Narodne Odbrane ", location: "MEJDAN" },
  { address: "Prvog Krajiškog Korpusa ", location: "TRANZIT" },
  /// R
  { address: "Rade Kondića ", location: "TRANZIT" },
  { address: "Rade Marjanca ", location: "LAUŠ" },
  { address: "Rade Marjanca brojevi do 7 N i 14 P ", location: "TRANZIT" },
  { address: "Rade Radića ", location: "MEJDAN" },
  { address: "Rade Vranješević ", location: "BORIK" },
  { address: "Radenka Lolića (pavlovac) ", location: "LAUŠ" },
  { address: "Radoja Domanovića ", location: "TROPIK" },
  { address: "Radomira Putnika ", location: "BORIK" },
  { address: "Radoslava Lakića ", location: "TRANZIT" },
  { address: "Rajka Bosnića ", location: "MEJDAN" },
  { address: "Radovana Vulina ", location: "BUDŽAK" },
  { address: "Rakovačkih Rudara ", location: "TRANZIT" },
  { address: "Ranka Miličevića ", location: "TRANZIT" },
  { address: "Ranka Šipke ", location: "TRANZIT" },
  { address: "Raška ", location: "TROPIK" },
  { address: "Ravnih Kotara ", location: "LAUŠ" },
  { address: "Ravnogorska ", location: "TRANZIT" },
  { address: "Relje Kneževića ", location: "LAUŠ" },
  { address: "Relje Krilatice ", location: "BORIK" },
  { address: "Romanijska ", location: "TRANZIT" },
  /// S
  { address: "Saničkih Žetalaca ", location: "MEJDAN" },
  { address: "Sanska ", location: "LAUŠ" },
  { address: "Sarajevska ", location: "ČESMA" },
  { address: "Save Kovačevića ", location: "BORIK" },
  { address: "Save Ljuboje ", location: "MEJDAN" },
  { address: "Save Mrkalja ", location: "TROPIK" },
  { address: "Save Šumanovića (Krčmarice) ", location: "BUDŽAK" },
  { address: "Save Tekelije ", location: "BUDŽAK" },
  { address: "Savska ", location: "BUDŽAK" },
  { address: "Sestara Levi ", location: "ČESMA" },
  { address: "Sime Matavulja/Ante Jakića ", location: "TROPIK" },
  { address: "Sime Milić Jorgić ", location: "LAUŠ" },
  { address: "Sime Miljuša ", location: "MEJDAN" },
  { address: "Sime Pandurevića ", location: "LAUŠ" },
  { address: "Sime Šolaje ", location: "BORIK" },
  { address: "Simeuna Đaka ", location: "TROPIK" },
  { address: "Siniše Mijatovića ", location: "MEJDAN" },
  { address: "Slatinska ", location: "BUDŽAK" },
  { address: "Slavka Rodića ", location: "TROPIK" },
  { address: "Slobodana Dubočanina ", location: "MEJDAN" },
  { address: "Slobodana Jovanovića ", location: "TRANZIT" },
  { address: "Slobodana Kusturića ", location: "MEJDAN" },
  { address: "Sokolovac ", location: "TROPIK" },
  { address: "Solunska ", location: "TROPIK" },
  { address: "Srđe Zlopogleđe ", location: "MEJDAN" },
  { address: "Srednjoškolska ", location: "BUDŽAK" },
  { address: "Sretena Stojanovića ", location: "BUDŽAK" },
  { address: "Srpska ", location: "BORIK" },
  { address: "Srpskih Dobrovoljaca ", location: "MEJDAN" },
  { address: "Srpskih Pilota ", location: "TRANZIT" },
  { address: "Srpskih Sokolova ", location: "LAUŠ" },
  { address: "Srpskih Ustanika ", location: "MEJDAN" },
  { address: "Srpskih Vitezova ", location: "TROPIK" },
  { address: "Skendera Kulenovića ", location: "TROPIK" },
  { address: "Starine Novaka ", location: "MEJDAN" },
  { address: "Starog Vujadina ", location: "MEJDAN" },
  { address: "Stefana Dečanskog ", location: "MEJDAN" },
  { address: "Stevana Bulajića ", location: "MEJDAN" },
  { address: "Stevana Markovića ", location: "TRANZIT" },
  { address: "Stevana Mokranjca ", location: "TRANZIT" },
  { address: "Stevana Moljevića ", location: "TROPIK" },
  { address: "Stevana Musića ", location: "BUDŽAK" },
  { address: "Stevana Prvovjenčanog ", location: "MEJDAN" },
  { address: "Stojana Jankovića ", location: "BUDŽAK" },
  { address: "Stojana Novakovića ", location: "TROPIK" },
  { address: "Studenička ", location: "MEJDAN" },
  { address: "Subotička ", location: "BUDŽAK" },
  { address: "Suturlija ", location: "TROPIK" },
  { address: "Sv. Kraljice Jelene ", location: "LAUŠ" },
  { address: "Svetog Nikole ", location: "LAUŠ" },
  { address: "Srpskih Rudara ", location: "LAUŠ" },
  { address: "Svetozara Ćorovića ", location: "LAUŠ" },
  /// T
  { address: "Talijanskog Bataljona Mateoti ", location: "TROPIK" },
  { address: "Tarasa Ševčenka ", location: "TRANZIT" },
  { address: "Tešana Podrugovića ", location: "MEJDAN" },
  { address: "Tihomira Damjanovića ", location: "MEJDAN" },
  { address: "Tina Ujevića ", location: "TRANZIT" },
  { address: "Todora od Stalaća ", location: "MEJDAN" },
  { address: "Trive Amelice ", location: "TRANZIT" },
  { address: "Trla ", location: "LAUŠ" },
  { address: "Tromeđe ", location: "TRANZIT" },
  { address: "Tuzlanska ", location: "MEJDAN" },
  /// U
  { address: "Uroša Drenovića (lijeva novoselija)", location: "TROPIK" },
  { address: "Uroša Nejakog ", location: "TROPIK" },
  { address: "Uroša Predića ", location: "BORIK" },
  { address: "Ustanički Put ", location: "MEJDAN" },
  { address: "Užička ", location: "LAUŠ" },
  /// V
  { address: "Vaclava Havleka Vene ", location: "MEJDAN" },
  { address: "Vase Glušca ", location: "BORIK" },
  { address: "Vase Kondića ", location: "TRANZIT" },
  { address: "Vase Pelagića ", location: "BORIK" },
  { address: "Vase Vidovića ", location: "BUDŽAK" },
  { address: "Velebitska ", location: "LAUŠ" },
  { address: "Velimira Čovića ", location: "LAUŠ" },
  { address: "Veljka Mlađenovića ", location: "BORIK" },
  { address: "Veselina Masleše ", location: "TROPIK" },
  { address: "Vida Nježića ", location: "MEJDAN" },
  { address: "Vida Simurdžića ", location: "LAUŠ" },
  { address: "Vidovdanska ", location: "TROPIK" },
  { address: "Vilsonova ", location: "MEJDAN" },
  { address: "Vasilija Ostroškog ", location: "BUDŽAK" },
  { address: "Visokih Dečana ", location: "MEJDAN" },
  { address: "Vladike Platona ", location: "BORIK" },
  { address: "Vladike Varnave Nastića ", location: "LAUŠ" },
  { address: "Vladimira Rolovića ", location: "LAUŠ" },
  { address: "Vladimira Zvonara ", location: "BUDŽAK" },
  { address: "Vladislava Skarića ", location: "BORIK" },
  { address: "Vlašićka ", location: "LAUŠ" },
  { address: "Vojvođanska ", location: "TRANZIT" },
  { address: "Vojvode Momčila ", location: "TROPIK" },
  { address: "Vojvode Prijezde ", location: "BUDŽAK" },
  { address: "Vojvode Sinđelića ", location: "TRANZIT" },
  { address: "Voždovačka ", location: "TRANZIT" },
  { address: "Vrbaski put ", location: "BORIK" },
  { address: "Vuka Karadžića ", location: "TRANZIT" },
  /// Z
  { address: "Zdrave Korde ", location: "TROPIK" },
  { address: "Zdravka Čelara ", location: "TROPIK" },
  { address: "Zdravka Dejanovića ", location: "ČESMA" },
  { address: "Zelengorska ", location: "LAUŠ" },
  { address: "Zmaj Jovina ", location: "TROPIK" },
  { address: "Zmaj Ognjenog Vuka ", location: "BUDŽAK" },
  { address: "Zmijanjska ", location: "TROPIK" },
  { address: "Zore Kovačević ", location: "TRANZIT" },
  { address: "Zvjezdana Mandića (lijeva novoselija) ", location: "TROPIK" },
  /// Š
  { address: "Šargovačka ", location: "BUDŽAK" },
  { address: "Šarplaninska ", location: "TRANZIT" },
  { address: "Špire Bocerića ", location: "LAUŠ" },
  { address: "Šumadijska ", location: "BUDŽAK" },
  /// Ž
  { address: "Žarka Zgonjanina ", location: "LAUŠ" },
  { address: "Željezničkih kolonija ", location: "BUDŽAK" },
  { address: "Živka Nježića ", location: "BUDŽAK" },
  { address: "Živojina Mišića ", location: "BORIK" },
  { address: "Živojina Preradovića ", location: "TRANZIT" },
];

export default base;
